{% set version = "4.6.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mlpack
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mlpack_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mlpack/mlpack_{{ version }}.tar.gz
  sha256: 0db9ef0e250c3995ca9b3cac6c9b075623301226943cf87a617f3d480c04fa6f

build:
  number: 0
  skip: true  # [r_base == "4.2" or win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.12
    - r-rcpparmadillo >=0.9.800
    - r-rcppensmallen >=0.2.10.0
    - libblas
    - liblapack
    - libgomp                      # [linux]
    - llvm-openmp                  # [osx]
  run:
    - r-base
    - r-rcpp >=0.12.12
    - r-rcpparmadillo >=0.9.800
    - r-rcppensmallen >=0.2.10.0

test:
  commands:
    - $R -e "library('mlpack')"           # [not win]
    - "\"%R%\" -e \"library('mlpack')\""  # [win]

about:
  home: https://www.mlpack.org/doc/mlpack-git/r_documentation.html
  dev_url: https://github.com/mlpack/mlpack
  license: BSD-3-Clause
  summary: A fast, flexible machine learning library, written in C++, that aims to provide fast, extensible implementations of cutting-edge machine learning algorithms.  See also Curtin et al. (2018) <doi:10.21105/joss.00726>.
  license_family: BSD
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - coatless
    - eddelbuettel
    - rcurtin
    - zoq
    - Yashwants19
